# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Set Next.js to use Netlify
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Essential redirects for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# API routes redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Next.js plugin for optimal performance
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
